services:
  ui:
    build:
      context: .
      args:
        VITE_API_URL: https://mirvari.devl0pr.com
    container_name: onepoint-ui
    restart: unless-stopped
    environment:
      API_URL: http://onepoint_nginx
    networks:
      - default
      - onepoint
    extra_hosts:
      - "mirvari.devl0pr.com:host-gateway"
    ports:
      - "127.0.0.1:8082:3000"

networks:
  onepoint:
    external: true
    name: onepoint_default
